import MainFooter from "@/components/ui/main-footer";
import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//RootLayout is not an reserved name
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
