import MainFooter from "@/components/main-footer";
import "../globals.css";
import QuestionsProvider from "@/context/QuestionsContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//RootLayout is not an reserved name
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <QuestionsProvider>
          {children}
          <MainFooter />
        </QuestionsProvider>
      </body>
    </html>
  );
}
