import UserHeader from "@/components/user-header";
import "../globals.css";
import QuestionsProvider from "@/context/QuestionsContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//RootLayout is not an reserved name
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserHeader />
        {children}
      </body>
    </html>
  );
}
